codecov:
  require_ci_to_pass: true


comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
        target: 80%        # minimum overall coverage
        threshold: 1%      # allow small drop
        if_not_found: failure
        if_ci_failed: error

    patch:
      default:
        target: 80%        # enforce coverage on changed code
        if_not_found: failure
        if_ci_failed: error
